In [2]:
# Dependencies and Setup
import requests
import json
import pandas as pd
import os

## Import the Priceline API key
from api_keys import priceline_api_key

In [14]:
# List of cities
city_list = [
    'San Jose, CA',
    'Santa Cruz, CA',
    'Newport Beach, CA',
    'Napa, CA',
    'Santa Monica, CA',
    'Long Beach, CA',
    'Fresno, CA',
    'Monterey, CA',
    'Santa Barbara, CA',
    'Palm Springs, CA',
    'Sacramento, CA',
    'Anaheim, CA',
    'San Diego, CA',
    'Los Angeles, CA',
    'San Francisco, CA',
    'San Luis Obispo, CA',
    'Carmel-by-the-Sea, CA',
    'Laguna Beach, CA',
    'Morro Bay, CA',
    'San Clemente, CA',
    'Catalina Island, CA',
    'Pismo Beach, CA',
    'Big Bear Lake, CA',
    'Pasadena, CA',
    'Carlsbad, CA',
    'Yosemite, CA',
    'Huntington Beach, CA',
    'Lake Tahoe, CA',
    'Eureka, CA',
    'Bakersfield, CA',
    'Oceanside, CA'
    
]

# Initialize an empty list to store DataFrames
dfs = []  
        
# Loop through each city in the list
for city in city_list:
    url = "https://priceline-com-provider.p.rapidapi.com/v1/hotels/locations"
    
    querystring = {"name": city, "search_type": "HOTEL"}

    headers = {
        "X-RapidAPI-Key": priceline_api_key,
        "X-RapidAPI-Host": "priceline-com-provider.p.rapidapi.com"
    }
    
    while True:
        response = requests.get(url, headers=headers, params=querystring)

        if response.status_code == 200:
            # Get the JSON data
            json_data = response.json()

            # Check if response type is "HOTEL"
            if json_data[0].get('type') == 'HOTEL':
                
                # Load the JSON response data into a list
                list_data = json.loads(response.text)
        
                # Create a DataFrame for the current city and append it to the list
                hotel_data = pd.DataFrame(list_data)
                dfs.append(hotel_data)
                
                break  # Exit the while loop if data is successfully retrieved
            else:
                print(f"Response type for {city} is not 'HOTEL'. Retrying...")
        else:
            print(f"Failed to get data for {city}. Status code:", response.status_code)
            break  # Exit the while loop on error

Response type for Santa Cruz, CA is not 'HOTEL'. Retrying...
Response type for Napa, CA is not 'HOTEL'. Retrying...
Response type for Monterey, CA is not 'HOTEL'. Retrying...
Response type for Monterey, CA is not 'HOTEL'. Retrying...
Response type for Sacramento, CA is not 'HOTEL'. Retrying...
Response type for San Diego, CA is not 'HOTEL'. Retrying...
Response type for San Diego, CA is not 'HOTEL'. Retrying...
Response type for San Diego, CA is not 'HOTEL'. Retrying...
Response type for San Diego, CA is not 'HOTEL'. Retrying...
Response type for San Francisco, CA is not 'HOTEL'. Retrying...
Response type for Laguna Beach, CA is not 'HOTEL'. Retrying...
Response type for San Clemente, CA is not 'HOTEL'. Retrying...
Response type for Big Bear Lake, CA is not 'HOTEL'. Retrying...
Response type for Big Bear Lake, CA is not 'HOTEL'. Retrying...
Response type for Big Bear Lake, CA is not 'HOTEL'. Retrying...
Response type for Pasadena, CA is not 'HOTEL'. Retrying...
Response type for Yosemite, CA is not 'HOTEL'. Retrying...
Response type for Yosemite, CA is not 'HOTEL'. Retrying...
Response type for Yosemite, CA is not 'HOTEL'. Retrying...
Response type for Lake Tahoe, CA is not 'HOTEL'. Retrying...
Response type for Lake Tahoe, CA is not 'HOTEL'. Retrying...
Response type for Eureka, CA is not 'HOTEL'. Retrying...
Response type for Eureka, CA is not 'HOTEL'. Retrying...
Response type for Eureka, CA is not 'HOTEL'. Retrying...
Response type for Bakersfield, CA is not 'HOTEL'. Retrying...
Response type for Bakersfield, CA is not 'HOTEL'. Retrying...
Response type for Bakersfield, CA is not 'HOTEL'. Retrying...
Response type for Bakersfield, CA is not 'HOTEL'. Retrying...
Response type for Bakersfield, CA is not 'HOTEL'. Retrying...

In [15]:
# Concatenate all DataFrames in the list into a single DataFrame
final_df = pd.concat(dfs, ignore_index=True)

# Print the final DataFrame
final_df

,itemName,id,cityID,type,lat,lon,proximity,savedTravelStartDate,savedTravelEndDate,cityName,...,poiCategoryTypeId,poiCategoryName,poiID,seType,gmtOffset,entered,highlightedName,displayLine1,displayLine2,fromSavedSearch
0,"Roseview House - San Jose, CA",125194804,3000002250,HOTEL,37.330200,-121.897280,0.0,None,None,San Jose,...,0,None,None,None,-7.0,san jose ca,None,Roseview House,"San Jose, California",False
1,"Boutique Hotel Calle 20 - San Jose, Costa Rica",13453403,3000070002,HOTEL,9.937550,-84.087102,0.0,None,None,San Jose,...,0,None,None,None,-6.0,san jose ca,None,Boutique Hotel Calle 20,"San Jose, Costa Rica",False
2,"Casa Lima B&B - San Jose, Costa Rica",42958406,3000070002,HOTEL,9.945148,-84.125250,0.0,None,None,San Jose,...,0,None,None,None,-6.0,san jose ca,None,Casa Lima B&B,"San Jose, Costa Rica",False
3,"El Mirador Del Valle - San Jose Del Valle, Spain",23075205,5000371869,HOTEL,36.612899,-5.804481,0.0,None,None,San Jose Del Valle,...,0,None,None,None,2.0,san jose ca,None,El Mirador Del Valle,"San Jose Del Valle, Spain",False
4,"Hostal San Carlos - Lloret De Mar, Spain",55974405,5000300440,HOTEL,41.701133,2.846687,0.0,None,None,Lloret De Mar,...,0,None,None,None,2.0,san jose ca,None,Hostal San Carlos,"Lloret De Mar, Spain",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,Updated Oceanside Townhome With Pool Walk TO B...,106244505,3000061781,HOTEL,21.092760,-86.769580,0.0,None,None,Cancun,...,0,None,None,None,-5.0,oceanside ca,None,Updated Oceanside Townhome With Pool Walk TO B...,"Cancun, Quintana Roo, Mexico",False
293,Ocean Dunes 5212 Sleeps Eight Pool Oceanside W...,171484503,3000019836,HOTEL,33.743270,-78.815910,0.0,None,None,Myrtle Beach,...,0,None,None,None,-4.0,oceanside ca,None,Ocean Dunes 5212 Sleeps Eight Pool Oceanside W...,"Myrtle Beach, South Carolina",False
294,On Oceanside And Clear Ocean Views Great Prici...,171484103,3000019836,HOTEL,33.743270,-78.815910,0.0,None,None,Myrtle Beach,...,0,None,None,None,-4.0,oceanside ca,None,On Oceanside And Clear Ocean Views Great Prici...,"Myrtle Beach, South Carolina",False
295,"Rodeway Inn Oceanside Marina - Oceanside, CA",5240705,3000002089,HOTEL,33.206600,-117.385200,0.0,None,None,Oceanside,...,0,None,None,None,-7.0,oceanside ca,None,Rodeway Inn Oceanside Marina,"Oceanside, California",False
296,"Ramada BY Wyndham Oceanside - Oceanside, CA",276802,3000002089,HOTEL,33.201514,-117.369469,0.0,None,None,Oceanside,...,0,None,None,None,-7.0,oceanside ca,None,Ramada BY Wyndham Oceanside,"Oceanside, California",False

In [16]:
final_df['name'] = final_df['displayLine1']
final_df['city'] = final_df['displayLine2'].str.split(',').str[0]
final_df['state'] = final_df['displayLine2'].str.split(',').str[1]

column_to_select = ['name',
                    'id',
                    'city',
                    'state',
                    'lat',
                    'lon',
                    'score', 
                    'rank', 
                    'rank2', 
                    'globalScore',
                    'country' 
                    ]

# Drop rows where a certain value is present in a specific column
values_to_keep = 'US'  # Replace with the value you want to drop
column_to_check = 'country'   # Replace with the column name

filtered_df_country = final_df[final_df[column_to_check] == values_to_keep]

# Drop rows where a certain value is present in a specific column
values_to_keep = 'HOTEL'  # Replace with the value you want to drop
column_to_check = 'type'   # Replace with the column name

filtered_df_type = filtered_df_country[filtered_df_country[column_to_check] == values_to_keep]

hotel_data_select = filtered_df_type[column_to_select]

# Drop duplicates based on the 'id' column, keeping the first occurrence
hotel_data_select = hotel_data_select.drop_duplicates(subset=['id'], keep='first')

hotel_data_select

,name,id,city,state,lat,lon,score,rank,rank2,globalScore,country
0,Roseview House,125194804,San Jose,California,37.330200,-121.897280,400808.88,1.000000,97.817245,1.0,US
10,Surf City Inn & Suites,42212,Santa Cruz,California,36.969860,-122.019880,400925.56,11.810301,97.820923,30.0,US
11,Villa Vista,71834504,Santa Cruz,California,36.955865,-121.977519,400922.38,1.000000,97.817245,1.0,US
12,Magical Oasis,77022303,Santa Cruz,California,36.956323,-122.025119,400921.44,0.500000,97.816200,1.0,US
20,Newport Beach Simplicity I & Ii,86227506,Newport Beach,California,33.615310,-117.932690,400936.80,0.500000,97.816200,30.0,US
...,...,...,...,...,...,...,...,...,...,...,...
288,Ocean View Compound,86210306,Oceanside,California,33.200380,-117.388660,400808.75,0.500000,97.816200,30.0,US
293,Ocean Dunes 5212 Sleeps Eight Pool Oceanside W...,171484503,Myrtle Beach,South Carolina,33.743270,-78.815910,398967.34,0.500000,97.816200,1.0,US
294,On Oceanside And Clear Ocean Views Great Prici...,171484103,Myrtle Beach,South Carolina,33.743270,-78.815910,398967.34,0.500000,97.816200,1.0,US
295,Rodeway Inn Oceanside Marina,5240705,Oceanside,California,33.206600,-117.385200,372648.22,12.239823,70.453796,30.0,US
296,Ramada BY Wyndham Oceanside,276802,Oceanside,California,33.201514,-117.369469,371396.16,11.810301,69.431206,30.0,US

In [7]:
hotel_data_select.dtypes

name            object
id              object
city            object
state           object
lat            float64
lon            float64
score          float64
rank           float64
rank2          float64
globalScore    float64
country         object
dtype: object

In [138]:
null_counts = hotel_data_select.isnull().sum()

print(null_counts)

name           0
id             0
city           0
state          0
lat            0
lon            0
score          0
rank           0
rank2          0
globalScore    0
country        0
dtype: int64

In [139]:
# Create a folder named "data" if it doesn't exist
if not os.path.exists("data"):
    os.mkdir("data")

# Save DataFrame to a CSV file inside the "data" folder
file_path = os.path.join("data", "hotel.csv")
hotel_data_select.to_csv(file_path, index=False)

print("DataFrame saved to 'data/hotel.csv' file.")

DataFrame saved to 'data/hotel.csv' file.

In [50]:
url = "https://priceline-com-provider.p.rapidapi.com/v1/hotels/locations"

querystring = {"name":"UNITED STATES","search_type":"AIRPORT"}

headers = {
	"X-RapidAPI-Key": priceline_api_key,
	"X-RapidAPI-Host": "priceline-com-provider.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

if response.status_code == 200:
    # Use json.dumps with 'indent' parameter to pretty-print the JSON data
    json_data = json.dumps(response.json(), indent=4)
    print(json_data)
else:
    print("Failed to get data. Status code:", response.status_code)

[
    {
        "itemName": "Orlando Intl Airport (MCO) , FL",
        "id": "MCO",
        "cityID": "3000003349",
        "type": "AIRPORT",
        "lat": 28.43113982264317,
        "lon": -81.3092428479283,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Orlando",
        "stateCode": "FL",
        "provinceName": "Florida",
        "score": 388071.66,
        "radius": 33.7,
        "rank": 56.13621,
        "rank2": 86.16417694091797,
        "globalScore": 78.25274,
        "globalScoreReducedCityBoost": 62.42079,
        "globalScoreWOHotelCountNormalize": 48.595905,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -4.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Orlando - Orlando Intl Airport (MCO)",
        "displayLine2": "Florida",
        "fromSavedSearch": false
    },
    {
        "itemName": "Miami Intl Airport (MIA) , FL",
        "id": "MIA",
        "cityID": "3000003311",
        "type": "AIRPORT",
        "lat": 25.79507559880528,
        "lon": -80.28296084528998,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Miami",
        "stateCode": "FL",
        "provinceName": "Florida",
        "score": 387476.03,
        "radius": 28.9,
        "rank": 45.91389,
        "rank2": 85.56851196289062,
        "globalScore": 76.66467,
        "globalScoreReducedCityBoost": 46.181736,
        "globalScoreWOHotelCountNormalize": 39.20895,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -4.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Miami - Miami Intl Airport (MIA)",
        "displayLine2": "Florida",
        "fromSavedSearch": false
    },
    {
        "itemName": "Hollywood Intl Airport (FLL) , FL",
        "id": "FLL",
        "cityID": "3000003192",
        "type": "AIRPORT",
        "lat": 26.076856242450617,
        "lon": -80.1512378481894,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Fort Lauderdale",
        "stateCode": "FL",
        "provinceName": "Florida",
        "score": 385823.97,
        "radius": 17.6,
        "rank": 57.068672,
        "rank2": 83.93750762939453,
        "globalScore": 75.521675,
        "globalScoreReducedCityBoost": 43.354076,
        "globalScoreWOHotelCountNormalize": 37.50558,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -4.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Fort Lauderdale - Hollywood Intl Airport (FLL)",
        "displayLine2": "Florida",
        "fromSavedSearch": false
    },
    {
        "itemName": "Hartsfield-Jackson Atlanta Intl Airport (ATL) , GA",
        "id": "ATL",
        "cityID": "3000003496",
        "type": "AIRPORT",
        "lat": 33.64064398331116,
        "lon": -84.42246632355115,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Atlanta",
        "stateCode": "GA",
        "provinceName": "Georgia",
        "score": 385106.66,
        "radius": 37.0,
        "rank": 42.474194,
        "rank2": 83.23897552490234,
        "globalScore": 76.96165,
        "globalScoreReducedCityBoost": 51.29527,
        "globalScoreWOHotelCountNormalize": 41.950603,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -4.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Atlanta - Hartsfield-Jackson Atlanta Intl Airport (ATL)",
        "displayLine2": "Georgia",
        "fromSavedSearch": false
    },
    {
        "itemName": "Phoenix Sky Harbor Intl Airport (PHX) , AZ",
        "id": "PHX",
        "cityID": "3000001349",
        "type": "AIRPORT",
        "lat": 33.43546779687481,
        "lon": -112.00379514445629,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Phoenix",
        "stateCode": "AZ",
        "provinceName": "Arizona",
        "score": 384922.3,
        "radius": 36.7,
        "rank": 47.539833,
        "rank2": 83.06039428710938,
        "globalScore": 74.87271,
        "globalScoreReducedCityBoost": 42.74244,
        "globalScoreWOHotelCountNormalize": 37.122154,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -7.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Phoenix - Phoenix Sky Harbor Intl Airport (PHX)",
        "displayLine2": "Arizona",
        "fromSavedSearch": false
    },
    {
        "itemName": "Tampa Intl Airport (TPA) , FL",
        "id": "TPA",
        "cityID": "3000003431",
        "type": "AIRPORT",
        "lat": 27.980050150536673,
        "lon": -82.53468498015411,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Tampa",
        "stateCode": "FL",
        "provinceName": "Florida",
        "score": 384829.53,
        "radius": 21.6,
        "rank": 46.03609,
        "rank2": 82.97066497802734,
        "globalScore": 75.06991,
        "globalScoreReducedCityBoost": 41.70141,
        "globalScoreWOHotelCountNormalize": 36.507195,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -4.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Tampa - Tampa Intl Airport (TPA)",
        "displayLine2": "Florida",
        "fromSavedSearch": false
    },
    {
        "itemName": "O'Hare Intl Airport (ORD) , IL",
        "id": "ORD",
        "cityID": "3000005381",
        "type": "AIRPORT",
        "lat": 41.9704762962616,
        "lon": -87.9083988449066,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Chicago",
        "stateCode": "IL",
        "provinceName": "Illinois",
        "score": 384373.72,
        "radius": 21.7,
        "rank": 46.816677,
        "rank2": 82.53114318847656,
        "globalScore": 76.78653,
        "globalScoreReducedCityBoost": 47.541634,
        "globalScoreWOHotelCountNormalize": 39.76,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -5.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Chicago - O'Hare Intl Airport (ORD)",
        "displayLine2": "Illinois",
        "fromSavedSearch": false
    },
    {
        "itemName": "Seattle-Tacoma Intl Airport (SEA) , WA",
        "id": "SEA",
        "cityID": "3000023414",
        "type": "AIRPORT",
        "lat": 47.44927062064107,
        "lon": -122.31113399152126,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Seattle",
        "stateCode": "WA",
        "provinceName": "Washington",
        "score": 384369.6,
        "radius": 28.0,
        "rank": 41.146538,
        "rank2": 82.52716827392578,
        "globalScore": 74.76679,
        "globalScoreReducedCityBoost": 42.604374,
        "globalScoreWOHotelCountNormalize": 37.04834,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -7.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Seattle - Seattle-Tacoma Intl Airport (SEA)",
        "displayLine2": "Washington",
        "fromSavedSearch": false
    },
    {
        "itemName": "John F Kennedy Intl Airport (JFK) , NY",
        "id": "JFK",
        "cityID": "3000015923",
        "type": "AIRPORT",
        "lat": 40.639380746613675,
        "lon": -73.77204034876185,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Jamaica",
        "stateCode": "NY",
        "provinceName": "New York",
        "score": 383816.5,
        "radius": 14.0,
        "rank": 51.016113,
        "rank2": 81.9969711303711,
        "globalScore": 77.9219,
        "globalScoreReducedCityBoost": 50.513313,
        "globalScoreWOHotelCountNormalize": 41.390118,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -4.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Jamaica - John F Kennedy Intl Airport (JFK)",
        "displayLine2": "New York",
        "fromSavedSearch": false
    },
    {
        "itemName": "Los Angeles Intl Airport (LAX) , CA",
        "id": "LAX",
        "cityID": "3000001947",
        "type": "AIRPORT",
        "lat": 33.94310840336072,
        "lon": -118.41060920960915,
        "proximity": 0.0,
        "savedTravelStartDate": null,
        "savedTravelEndDate": null,
        "cityName": "Los Angeles",
        "stateCode": "CA",
        "provinceName": "California",
        "score": 383285.62,
        "radius": 22.3,
        "rank": 58.362736,
        "rank2": 81.49127960205078,
        "globalScore": 76.51697,
        "globalScoreReducedCityBoost": 44.505028,
        "globalScoreWOHotelCountNormalize": 38.192566,
        "country": "US",
        "address": null,
        "zip": null,
        "countryName": "UNITED STATES",
        "countryCode": "US",
        "poiCategoryTypeId": 0,
        "poiCategoryName": null,
        "poiID": null,
        "seType": null,
        "gmtOffset": -7.0,
        "entered": "united states",
        "highlightedName": null,
        "displayLine1": "Los Angeles - Los Angeles Intl Airport (LAX)",
        "displayLine2": "California",
        "fromSavedSearch": false
    }
]

In [51]:
dictionary_data = json.loads(response.text)

airport_data = pd.DataFrame(dictionary_data)

airport_data

,itemName,id,cityID,type,lat,lon,proximity,savedTravelStartDate,savedTravelEndDate,cityName,...,poiCategoryTypeId,poiCategoryName,poiID,seType,gmtOffset,entered,highlightedName,displayLine1,displayLine2,fromSavedSearch
0,"Orlando Intl Airport (MCO) , FL",MCO,3000003349,AIRPORT,28.431140,-81.309243,0.0,None,None,Orlando,...,0,None,None,None,-4.0,united states,None,Orlando - Orlando Intl Airport (MCO),Florida,False
1,"Miami Intl Airport (MIA) , FL",MIA,3000003311,AIRPORT,25.795076,-80.282961,0.0,None,None,Miami,...,0,None,None,None,-4.0,united states,None,Miami - Miami Intl Airport (MIA),Florida,False
2,"Hollywood Intl Airport (FLL) , FL",FLL,3000003192,AIRPORT,26.076856,-80.151238,0.0,None,None,Fort Lauderdale,...,0,None,None,None,-4.0,united states,None,Fort Lauderdale - Hollywood Intl Airport (FLL),Florida,False
3,Hartsfield-Jackson Atlanta Intl Airport (ATL) ...,ATL,3000003496,AIRPORT,33.640644,-84.422466,0.0,None,None,Atlanta,...,0,None,None,None,-4.0,united states,None,Atlanta - Hartsfield-Jackson Atlanta Intl Airp...,Georgia,False
4,"Phoenix Sky Harbor Intl Airport (PHX) , AZ",PHX,3000001349,AIRPORT,33.435468,-112.003795,0.0,None,None,Phoenix,...,0,None,None,None,-7.0,united states,None,Phoenix - Phoenix Sky Harbor Intl Airport (PHX),Arizona,False

In [52]:
airport_data.columns

Index(['itemName', 'id', 'cityID', 'type', 'lat', 'lon', 'proximity',
       'savedTravelStartDate', 'savedTravelEndDate', 'cityName', 'stateCode',
       'provinceName', 'score', 'radius', 'rank', 'rank2', 'globalScore',
       'globalScoreReducedCityBoost', 'globalScoreWOHotelCountNormalize',
       'country', 'address', 'zip', 'countryName', 'countryCode',
       'poiCategoryTypeId', 'poiCategoryName', 'poiID', 'seType', 'gmtOffset',
       'entered', 'highlightedName', 'displayLine1', 'displayLine2',
       'fromSavedSearch'],
      dtype='object')

In [57]:
airport_data['name'] = airport_data['itemName'].str.split(',').str[0]
airport_data['city'] = airport_data['cityName']
airport_data['state'] = airport_data['displayLine2']

column_to_select = ['name',
                    'id',
                    'city',
                    'state',
                    'lat',
                    'lon',
                    'score', 
                    'rank', 
                    'rank2', 
                    'globalScore',
                    'country' 
                    ]

airport_data_select = airport_data[column_to_select]

airport_data_select.head()

,name,id,city,state,lat,lon,score,rank,rank2,globalScore,country
0,Orlando Intl Airport (MCO),MCO,Orlando,Florida,28.431140,-81.309243,388071.66,56.136210,86.164177,78.252740,US
1,Miami Intl Airport (MIA),MIA,Miami,Florida,25.795076,-80.282961,387476.03,45.913890,85.568512,76.664670,US
2,Hollywood Intl Airport (FLL),FLL,Fort Lauderdale,Florida,26.076856,-80.151238,385823.97,57.068672,83.937508,75.521675,US
3,Hartsfield-Jackson Atlanta Intl Airport (ATL),ATL,Atlanta,Georgia,33.640644,-84.422466,385106.66,42.474194,83.238976,76.961650,US
4,Phoenix Sky Harbor Intl Airport (PHX),PHX,Phoenix,Arizona,33.435468,-112.003795,384922.30,47.539833,83.060394,74.872710,US

In [64]:
airport_data_select.dtypes

name            object
id              object
city            object
state           object
lat            float64
lon            float64
score          float64
rank           float64
rank2          float64
globalScore    float64
country         object
dtype: object

In [66]:
null_counts = airport_data_select.isnull().sum()

print(null_counts)

name           0
id             0
city           0
state          0
lat            0
lon            0
score          0
rank           0
rank2          0
globalScore    0
country        0
dtype: int64

In [67]:
# Create a folder named "data" if it doesn't exist
if not os.path.exists("data"):
    os.mkdir("data")

# Save DataFrame to a CSV file inside the "data" folder
file_path = os.path.join("data", "airport.csv")
airport_data_select.to_csv(file_path, index=False)

print("DataFrame saved to 'data/airport.csv' file.")

DataFrame saved to 'data/airport.csv' file.

In [17]:
test = hotel_data_select.copy()

test["price"] = ""

In [18]:

for index, row in test.iterrows():
    
    url = "https://priceline-com-provider.p.rapidapi.com/v1/hotels/booking-details"
    
    date_checkin = "2023-10-18"
    date_checkout = "2023-10-19"
    hotel_id = row["id"]
    rooms_number = "1"

    querystring = {"date_checkin": date_checkin,"hotel_id": hotel_id,"date_checkout": date_checkout,"rooms_number": rooms_number}

    headers = {
	    "X-RapidAPI-Key": priceline_api_key,
	    "X-RapidAPI-Host": "priceline-com-provider.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers, params=querystring)
    
    response = response.json()
    
    try:
        test.loc[index, "price"] = response["rooms"][0]["displayableRates"][0]["displayPrice"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No hotel found".
        test.loc[index, "price"] = "No price found"

125194804 - price: No price found
42212 - price: 279.00
71834504 - price: No price found
77022303 - price: No price found
86227506 - price: No price found
86220506 - price: No price found
86205706 - price: No price found
86199806 - price: No price found
86209706 - price: No price found
86211506 - price: No price found
86200706 - price: No price found
86203606 - price: No price found
86219306 - price: No price found
165741304 - price: No price found
4536805 - price: No price found
147643504 - price: 719.98
122035703 - price: No price found
122040303 - price: No price found
46299306 - price: 470.35
43633 - price: 77.85
39373 - price: 339.00
40664 - price: 300.05
10114304 - price: 152.15
177202703 - price: No price found
39053 - price: 409.00
43607 - price: 209.20
9350505 - price: 649.00
17175204 - price: 539.10
43244 - price: 305.00
44061 - price: 179.10
39652 - price: 494.73
69378405 - price: 332.22
31380504 - price: 386.10
35908006 - price: No price found
29945705 - price: 137.61
45322505 - price: 90.00
131497003 - price: No price found
65781006 - price: No price found
39620 - price: 380.24
39820 - price: 183.60
43234 - price: 83.01
42760 - price: 407.15
4700605 - price: 79.99
39087 - price: 135.00
43093 - price: 58.65
41461 - price: 71.91
18708704 - price: 69.99
40564 - price: No price found
17783004 - price: 104.95
40066 - price: 192.96
1495705 - price: 73.00
17192704 - price: 62.69
7075305 - price: 70.00
18150504 - price: 107.14
26336603 - price: No price found
40572 - price: 219.00
60024405 - price: 80.00
86200406 - price: No price found
9580705 - price: 554.90
39499 - price: 376.28
40406 - price: 319.20
43196 - price: 245.52
147703604 - price: No price found
39032 - price: 307.80
41552 - price: 272.16
5477805 - price: 506.00
8556805 - price: No price found
40625 - price: No price found
3413005 - price: 278.10
116607705 - price: No price found
86802103 - price: 278.42
65747706 - price: No price found
36653703 - price: No price found
98326003 - price: No price found
41335 - price: 63.75
39598 - price: 296.24
18707604 - price: 59.99
3231805 - price: 133.20
40607605 - price: 99.00
156446003 - price: No price found
25785504 - price: 89.99
40206904 - price: 99.00
4008105 - price: 52.79
64690903 - price: No price found
17182204 - price: 119.70
41819 - price: 299.00
39542 - price: 344.08
41162 - price: 266.00
69015104 - price: 159.84
39941 - price: 101.15
5713805 - price: 142.49
4545405 - price: No price found
41580 - price: 287.10
727602 - price: 210.00
10051304 - price: 180.95
51721303 - price: No price found
80626204 - price: No price found
91219003 - price: No price found
116383803 - price: No price found
86201106 - price: No price found
43086 - price: 116.10
44170 - price: 89.25
39509 - price: 178.38
172917303 - price: 137.70
3238405 - price: 228.57
41313 - price: 595.00
17476603 - price: 157.00
2556003 - price: 244.64
42913903 - price: No price found
68975105 - price: No price found
101370904 - price: No price found
119753003 - price: 291.06
76861303 - price: No price found
119938704 - price: 347.65
40550 - price: 224.25
2185903 - price: 183.60
40959206 - price: No price found
42559 - price: 148.49
41391104 - price: 80.19
43023 - price: 89.10
31152804 - price: 62.99
2578205 - price: 95.27
3637305 - price: 259.00
61216505 - price: 68.70
3799704 - price: 63.00
104666105 - price: 260.00
39360 - price: 279.69
10309904 - price: 168.56
43026 - price: 82.00
2991505 - price: 134.10
43101 - price: 168.21
6171805 - price: 219.00
4088905 - price: 145.00
19051004 - price: 278.10
43217 - price: 193.50
40778 - price: No price found
9302603 - price: 225.72
41283 - price: 585.65
8424505 - price: 194.40
4559205 - price: 476.10
3068505 - price: 299.00
4061105 - price: 269.00
44223206 - price: 272.92
3004705 - price: 215.10
44230 - price: 116.24
7554705 - price: No price found
2991805 - price: 209.00
2991605 - price: 141.55
7150105 - price: No price found
4518305 - price: No price found
3021005 - price: 179.00
17632704 - price: 89.00
11099603 - price: 85.94
10953303 - price: 121.50
86213206 - price: No price found
86199606 - price: No price found
60239604 - price: 269.00
5591504 - price: 170.00
5554503 - price: No price found
129661003 - price: No price found
40750 - price: 98.10
36368803 - price: 255.27
39873 - price: 135.15
5653505 - price: 162.00
9237305 - price: 239.00
41069 - price: 249.00
47322305 - price: 98.10
133482104 - price: 449.00
4455105 - price: 157.50
26228003 - price: 220.97
74448105 - price: No price found
107041804 - price: 179.10
125373003 - price: No price found
5603205 - price: 133.99
1964105 - price: 132.00
42972606 - price: 117.00
5501803 - price: 74.88
40671 - price: 161.10
16904603 - price: 185.76
9459504 - price: 302.63
39535 - price: 246.40
39026 - price: 259.47
43118 - price: 103.70
474703 - price: 168.35
39859 - price: 164.36
39351 - price: 279.69
40024 - price: 224.10
5394605 - price: 141.00
86230706 - price: No price found
5594305 - price: 128.26
14588403 - price: 203.67
42466 - price: 139.50
1779903 - price: 94.99
1731405 - price: 67.99
29724006 - price: 242.25
41449 - price: 100.28
41301 - price: 96.39
87855403 - price: 460.00
41282804 - price: No price found
41169304 - price: No price found
41278104 - price: No price found
41197604 - price: No price found
28602803 - price: No price found
58081305 - price: No price found
34065604 - price: 152.44
43926 - price: 116.23
39614 - price: 320.45
1943603 - price: 425.00
43570 - price: 132.21
41731 - price: 141.37
50564803 - price: 274.00
43271 - price: 149.46
33336803 - price: 779.00
39985 - price: 109.00
1963005 - price: 234.11
26325803 - price: No price found
26339703 - price: No price found
26323203 - price: No price found
26338903 - price: No price found
26339103 - price: No price found
110315504 - price: No price found
55082106 - price: No price found
57772403 - price: 139.00
75104104 - price: No price found
155390903 - price: No price found
43282 - price: No price found
1808405 - price: No price found
31853204 - price: 156.40
39034 - price: 115.20
113004603 - price: 97.75
43948 - price: 129.99
43004 - price: 169.99
10184204 - price: 111.00
1763603 - price: 49.49
19798904 - price: 59.39
18927204 - price: 57.59
41009 - price: 70.30
40906 - price: 138.99
41800 - price: 92.65
18718704 - price: 53.99
43831 - price: 139.00
40334 - price: 93.24
77919206 - price: No price found
86210306 - price: No price found
171484503 - price: No price found
171484103 - price: No price found
5240705 - price: 68.08
276802 - price: 85.98

In [19]:
# Drop rows where a certain value is present in a specific column
values_to_drop = 'No price found'  # Replace with the value you want to drop
column_to_check = 'price'   # Replace with the column name

filtered_test = test[test[column_to_check] != values_to_drop]

len(filtered_test)

173

In [23]:
filtered_test

,name,id,city,state,lat,lon,score,rank,rank2,globalScore,country,price
10,Surf City Inn & Suites,42212,Santa Cruz,California,36.969860,-122.019880,400925.56,11.810301,97.820923,30.0,US,279.00
31,Silverado Golf Course,147643504,Napa,California,38.359940,-122.264030,400987.97,0.500000,97.816200,30.0,US,719.98
34,Inn On Randolph,46299306,Napa,California,38.292615,-122.287015,400987.97,0.500000,97.816200,30.0,US,470.35
36,Quality Inn Near Six Flags Discovery Kingdom-N...,43633,Vallejo,California,38.135570,-122.213600,375053.16,11.810301,74.033867,30.0,US,77.85
37,Embassy Suites BY Hilton Hotel Napa Valley,39373,Napa,California,38.297720,-122.300320,368351.38,13.473780,66.864861,30.0,US,339.00
...,...,...,...,...,...,...,...,...,...,...,...,...
284,"Motel 6-Bakersfield, CA - Airport",18718704,Bakersfield,California,35.415570,-119.060431,363192.56,11.810460,62.982529,30.0,US,53.99
285,Courtyard BY Marriott Bakersfield,43831,Bakersfield,California,35.380810,-119.048030,363191.62,11.823450,62.982460,30.0,US,139.00
286,Hampton Inn BY Hilton Bakersfield Central,40334,Bakersfield,California,35.367607,-119.039201,361070.03,11.836448,61.438564,30.0,US,93.24
295,Rodeway Inn Oceanside Marina,5240705,Oceanside,California,33.206600,-117.385200,372648.22,12.239823,70.453796,30.0,US,68.08
296,Ramada BY Wyndham Oceanside,276802,Oceanside,California,33.201514,-117.369469,371396.16,11.810301,69.431206,30.0,US,85.98

In [21]:
# Create a folder named "data" if it doesn't exist
if not os.path.exists("data"):
    os.mkdir("data")

# Save DataFrame to a CSV file inside the "data" folder
file_path = os.path.join("data", "hotel_price.csv")
filtered_test.to_csv(file_path, index=False)

print("DataFrame saved to 'data/hotel_price.csv' file.")

DataFrame saved to 'data/hotel_price.csv' file.

In [5]:
test = filtered_test.copy()

for index, row in test.iterrows():
    
    url = "https://priceline-com-provider.p.rapidapi.com/v1/hotels/booking-details"
    
    date_checkin = "2023-10-18"
    date_checkout = "2023-10-19"
    hotel_id = row["id"]
    rooms_number = "1"

    querystring = {"date_checkin": date_checkin,"hotel_id": hotel_id,"date_checkout": date_checkout,"rooms_number": rooms_number}

    headers = {
	    "X-RapidAPI-Key": priceline_api_key,
	    "X-RapidAPI-Host": "priceline-com-provider.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers, params=querystring)
    
    response = response.json()

        
    try:
        test.loc[index, "guestrating"] = response["overallGuestRating"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No rating found".
        test.loc[index, "guestrating"] = "No rating found"
        print(f"{test.loc[index, 'id']} - No rating found")

In [7]:
len(test[test["guestrating"] == "No rating found"])

5

In [9]:
# Drop rows where a certain value is present in a specific column
values_to_drop = 'No rating found'  # Replace with the value you want to drop
column_to_check = 'guestrating'   # Replace with the column name

filtered_test = test[test[column_to_check] != values_to_drop]

len(filtered_test)

# Create a folder named "data" if it doesn't exist
if not os.path.exists("data"):
    os.mkdir("data")

# Save DataFrame to a JSON file inside the "data" folder
json_data = filtered_test.to_json(orient='records')
file_path = os.path.join("data", "hotel_final.json")

with open(file_path, 'w') as json_file:
    json_file.write(json_data)

print("DataFrame saved to 'data/hotel_final.json' file.")

DataFrame saved to 'data/hotel_final.json' file.